- name: mongodb configuration
  hosts: mongodb
  become: yes
  tasks:
  # - name: mongodb package testt
    # ansible.builtin.package:
    #   name: "{{item}}"
    #   state: present
    # loop:
    # - git
    # - net-tools
  
  - name: mongodb repo file copy
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo
  
  - name: mongodb org install
    ansible.builtin.package:
      name: mongodb-org
      state: present

  - name: mongodb service start
    ansible.builtin.service:
      name: mongod
      enabled: yes
      state: started

  - name: Update listen address from 127.0.0.1 to 0.0.0.0 in /etc/mongod.conf
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  
  
  - name: mongodb service re-start
    ansible.builtin.service:
      name: mongod
      state: restarted

