- name: mongodb configuration
  hosts: mongodb
  become: yes
  tasks:
  - name: mongodb package testt
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    loop:
    - git
    - nettools